/*
 * SimulationParameters.java
 *
 * Created on October 29, 2007, 1:18 PM
 *
 */

package jp.ac.tut.tutkie.sys.srn.tournament;

/**
 *
 * @author tokumitsu
 */
public interface SimulationParameters {
    String SPACE_HEIGHT = "SPACE_HEIGHT";
    String SPACE_WIDTH = "SPACE_WIDTH";
    String ALL_AGENT_COUNT = "ALL_AGENT_COUNT";
    String NORMAL_PROBABILITY_AT_INITIAL = "NORMAL_PROBABILITY_AT_INITIAL";
    String UNIT_CLASS_NAME = "UNIT_CLASS_NAME";
    String FAILURE_RATE = "FAILURE_RATE";
    String FAILURE_RATE_CYCLE = "FAILURE_RATE_CYCLE";
    String DAMAGE_RATE = "DAMAGE_RATE";
    String REPAIR_TRIAL_RATE = "REPAIR_TRIAL_RATE";
    String REPAIR_SUCCESS_RATE_BY_NORMAL = "REPAIR_SUCCESS_RATE_BY_NORMAL";
    String REPAIR_SUCCESS_RATE_BY_ABNORMAL = "REPAIR_SUCCESS_RATE_BY_ABNORMAL";
    String MAX_RESOURCE = "MAX_RESOURCE";
    String REPAIR_RESOURCE = "REPAIR_RESOURCE";
    String NEIGHBOR_RADIUS = "NEIGHBOR_RADIUS";
    String NEIGHBOR_UNIT_COUNT = "NEIGHBOR_UNIT_COUNT";
    String STRATEGY_UPDATE_CYCLE = "STRATEGY_UPDATE_CYCLE";
    String STRATEGY_UPDATE_ERROR_RATE = "STRATEGY_UPDATE_ERROR_RATE";
    String REPAIR_STRATEGY_A = "REPAIR_STRATEGY_A";
    String REPAIR_STRATEGY_B = "REPAIR_STRATEGY_B";
    String DUMP_NETWORK_CONFIGURATION = "DUMP_NETWORK_CONFIGURATION";

}